### ISSUE TITLE
GNOME 40 runtime is EOL'ed, please migrate to a supported platform

### ISSUE THREAD

**Issue by rayrrr** [theironrobin/siglo#107]
While attempting to cross-compile for PinePhone, on this step:

`flatpak install --user flathub org.gnome.Sdk/aarch64/40 org.gnome.Platform/aarch64/40`

I saw this message:

> Info: (pinned) org.gnome.Sdk//40 is end-of-life, with reason:
>   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.

...so I'm asking for exactly that. Thanks!

Edit: I tried to follow through with all the instructions but on the last step, trying to install the app on the PinePhone Pro (running Mobian), I get the message

> The application com.github.alexr4535.siglo/aarch64/master requires the runtime org.gnome.Platform/aarch64/40 which was not found

**Comment by rayrrr** [comment]
Hi again, I'm quite new to developing for the phone platform, so pardon the naive approach. I tried cross-compiling with Gnome version 40, version 41, and version 42. I installed dependencies as necessary. Nothing works for the PPP (PinePhone Pro).

I even tried directly compiling it on the PPP, and that gets me to what seems like a successful install with a "desktop" icon for Siglo appearing, but when I try to tap on that icon to open Siglo, it just displays a splash screen with the Siglo logo and then silently crashes.

Please let me know what else I can do to help as the owner of a PPP to get this app running on said device.

FWIW, the default version in the latest Mobian appears to be 41.

**Comment by alex-startengine** [comment]
rayrrr: what kind of output do you get when running `siglo` from command line?

**Comment by rayrrr** [comment]
@alex-startengine I was able to actually get it to run on Mobian after all by compiling directly on the PPP.

**Comment by alexr4535** [comment]
ok good.
