### ISSUE TITLE
Siglo not working on Pinephone?

### ISSUE THREAD

**Issue by tootbrute** [theironrobin/siglo#109]
1. Tried flatpak.
- installs fine
- opens but cannot find my Pinetime
- uninstalled to try compiling it or maybe i'm "doing it wrong"

2. Compiled it using instructions from the github repo
- siglo can open but cannot connect to my phone
- i also don't even really know what steps I should be doing.
- i tried mashing "try again" button alot. i tried turning the bluetooth off and on for my phone and pinetime. i tried connecting through pinephone bluetooth.
- if i connect pinephone to pinetime it shows bluetooth connection on pinetime but it doesn't last.
```
mobian@mobian:~$ siglo
Start scanning
Start scanning
Start scanning
Start scanning
Start scanning
Start scanning
Start scanning
Start scanning

(process:3257): Gtk-CRITICAL **: 16:53:44.478: gtk_style_context_add_provider_for_>
Start scanning
Start scanning

```

Information about my Pinephone Beta:
```
$ neofetch --off
mobian@mobian 
------------- 
OS: Debian GNU/Linux bookworm/sid aarch64 
Host: Pine64 PinePhone (1.2) 
Kernel: 5.15-sunxi64 
Uptime: 20 mins 
Packages: 1501 (dpkg), 22 (flatpak) 
Shell: bash 5.1.16 
Resolution: 720x1440 
Terminal: /dev/pts/0 
CPU: (4) @ 1.152GHz 
Memory: 1006MiB / 2995MiB
```

**Comment by tootbrute** [comment]
Ok I think the app works.

- I rebooted Pinetime
- Right after it rebooted, I pressed "Try Again" a few times in Siglo
- It finds Pinetime.
- I click Keep Paired.

Is this app supposed to make Pinephone get notifications for Pinetime?
Is this app only for updating firmware?

I'm a bit confused about the purpose of this app and what its capabilities are.

**Comment by theironrobin** [comment]
Yeah siglo really just updates firmware and syncs the time at this point. I am working on more functionality to keep it paired.
