### ISSUE TITLE
gatt dependency

### ISSUE THREAD

**Issue by mc0e** [theironrobin/siglo#112]
I followed the build/install instructions (with the variation that I had to update meson along the way), but siglo won't run:

```
~/src/siglo/build $ siglo
Traceback (most recent call last):
  File "/usr/local/bin/siglo", line 46, in <module>
    main()
  File "/usr/local/bin/siglo", line 28, in main
    from siglo import daemon
  File "/usr/local/share/siglo/siglo/daemon.py", line 1, in <module>
    import gatt
ModuleNotFoundError: No module named 'gatt'
```

`pip3 install gatt` fixes the installation, but this needs to be recognised during the build, and if it's not to be installed automatically, then the user steps should be documented.

**Comment by alex-startengine** [comment]
Refer to https://github.com/theironrobin/siglo#readme for a full list of dependancies

**Comment by theironrobin** [comment]
https://github.com/theironrobin/siglo/blob/main/README.md has a full list of deps and how to install them for multiple distros. Do you know a better way of doing it?

**Comment by mc0e** [comment]
You've got instructions in the README.md file which currently are likely to fail.  Even just referencing the list of dependencies you have in the requirements section of that page would be a significant step.

Better would be to have your build system check for the availability of its dependencies and either install them as required, or at least produce warnings at build time rather than leave it to fail at run time.  I have very rarely seen meson before, so I'm not familiar with how meson implements such things.
