### ISSUE TITLE
Siglo is not finding my pinetime

### ISSUE THREAD

**Issue by sirnewton01** [theironrobin/siglo#3]
I've been trying siglo to scan and find my pinetime, but it doesn't seem to be able to find it on the network. I'm able to connect to it using bluetoothctl though. Perhaps I need to update the old firmware on the device? It's the 0.7.1 that came with the device last winter.

**Comment by alexr4535** [comment]
What distro are you on?
Are you sure you have all dependencies installed?
What kind of output do you get when running siglo from terminal?

**Comment by sirnewton01** [comment]
I think I have all the dependencies installed on Mobian, but perhaps I'm missing something. I tried translating the packages to the Debian equivalents. Thanks for your help with this. I know that Mobian/Debian may not be what you're targeting with this application.

The output when run from the terminal is just this:
```
Rescan button clicked...
Rescan button clicked...
Rescan button clicked...
```

**Comment by alexr4535** [comment]
Thanks for the output, I will install siglo soon on mobian and see what the issue could be.

**Comment by alexr4535** [comment]
Ok, I think i solved the bug here: https://github.com/alexr4535/siglo/commit/97977260b0176b8a984021c17c825357336abc41

Don't think your issue is due to distro, but due to using old firmware. Siglo should now work will old firmware that describes itself to BLE adapter as "Pinetime-JF"

**Comment by sirnewton01** [comment]
Thanks @alexr4535 it's working great now. You've saved me a bunch of time manually converting the date into a the hex format and manually setting it to the watch using bluetoothctl.

Btw, any plans to support firmware upgrades over the air with Siglo? I should probably upgrade this ancient firmware to something better.

**Comment by alexr4535** [comment]
You're welcome! OTA updates will be supported with the next version of Siglo, give me a week or two.

**Comment by sirnewton01** [comment]
Yay! Thanks, looking forward to giving it a try.

**Comment by apoorv569** [comment]
Hi, I am having same problem, I am on Arch Linux, I installed `Siglo` from `AUR`, also tried cloning and building my self. No luck. If I open `Siglo` from terminal no error is shown when I click scan button it just says `Start scanning`. I can connect the watch to my phone using `GadgetBridge` fine though. I tried with connecting watch with version `0.7.1` and `1.0.0`.

**Comment by Flone-dnb** [comment]
> Hi, I am having same problem, I am on Arch Linux, I installed `Siglo` from `AUR`, also tried cloning and building my self. No luck. If I open `Siglo` from terminal no error is shown when I click scan button it just says `Start scanning`. I can connect the watch to my phone using `GadgetBridge` fine though. I tried with connecting watch with version `0.7.1` and `1.0.0`.

Same here, InfiniTime version 1.2.0. Siglo can't find my device.

**Comment by alexr4535** [comment]
open with the terminal and post output please

**Comment by wilsonjholmes** [comment]
I have the same issue.
![image](https://user-images.githubusercontent.com/59266497/129141236-96696d3f-370e-43c1-879e-32ad9fb26c83.png)
![image](https://user-images.githubusercontent.com/59266497/129141266-490c3ee4-3286-4581-8c43-426ca65d15b8.png)
![image](https://user-images.githubusercontent.com/59266497/129141343-0419aee1-7191-42d5-a0a9-094e0930cb4f.png)

**Comment by kq98** [comment]
Did you reset the watch before trying to pair? Because according to [#207 Infinitime](https://github.com/JF002/InfiniTime/issues/207) the BLE functionality of Infinitime breaks down after about 20 hours of uptime.

**Comment by mshayden** [comment]
> Did you reset the watch before trying to pair? Because according to [#207 Infinitime](https://github.com/JF002/InfiniTime/issues/207) the BLE functionality of Infinitime breaks down after about 20 hours of uptime.

This is still an issue for me as well...pinephone with Mobian and a new PineTime with InfiniTime 1.2 factory installed. Console output is just "start scanning" as mentioned in a previous comment.

[#207 Infinitime](https://github.com/JF002/InfiniTime/issues/207) is not an issue as the watch uptime was only 30 minutes.

Is there a way to enable some useful level of debugging output?

**Comment by alexr4535** [comment]
> Is there a way to enable some useful level of debugging output?

Besides running from the console, not really. I am told siglo doesn't like the waspos bootloader. Maybe that is the issue. I wrote siglo to only support Infinitime

**Comment by alexr4535** [comment]
> Does the factory installed version of InfiniTime somehow use the WaspOS bootloader instead? 

It sealed pinetime should come with the right bootloader for siglo. I'm sorry you are having issues. 

infinitime might stop advertising after 30 minutes if left unpaired, i would reboot the watch (hold the button on the side) and try again with siglo.

**Comment by loveisfoss** [comment]
Hey, just thought I would share that I also have the same  problem. The watch is seen in the bluetooth settings (not  paired) but it is not found in Siglo.

Siglo flatpak version
Pinephone with Mobian
InfiniTime 1.6.0, stock bootloader

**Comment by InFerYes** [comment]
I have InfiniTime 1.6.0 and my PineTime is unpaired. It can be discovered via the Bluetooth settings panel in phosh, however the PineTime does not connect to Siglo. It's possible to connect via the Bluetooth settings panel, but either way (connected or not) Siglo does not connect.

The console says `Start scanning` over and over. The device is detected as `InfiniTime` over bluetooth.

**Comment by apoorv569** [comment]
I tried using `Siglo` again today on my new laptop that I bought 4 days ago and it seems to find my `PineTime` with firmware version `1.7.0` and connect just fine. I am on `ArchLinux` and I installed `Siglo` from `AUR`. So for me the issue is solved, I can't say what fixed it though.

**Comment by gregg00** [comment]
I am trying to flash firmware on my PineTime with my PinePhone and am having the same problems as other users.
PinePhone sees PineTime and can connect to PineTime in PinePhone bluetooth settings, but is not able to connect to the PineTime with the Siglo app (flatpak v0.9.4).  PineTime firmware is 0.7.1 in PinePhone bluetooth settings PineTime is listed as Y7S
